# Generated by Django 5.2.1 on 2025-05-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TamptoProject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sajili",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
