# Generated by Django 5.2.1 on 2025-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TamptoProject", "0003_alter_sajili_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="michango",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="michango",
            name="phone_no",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="sajili",
            name="phone_no",
            field=models.CharField(max_length=12),
        ),
    ]
