# Generated by Django 5.2.1 on 2025-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TamptoProject", "0004_michango_is_seen_alter_michango_phone_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="michango",
            name="phone_no",
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name="michango",
            name="regions",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="sajili",
            name="phone_no",
            field=models.CharField(max_length=17),
        ),
    ]
