# Generated by Django 5.2.1 on 2025-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TamptoProject",
            "0005_alter_michango_phone_no_alter_michango_regions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sajili",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
